#!/usr/local/bin/env python
# Author: dreamclinger@gmail.com
# Create: 2014/12/06
# Bucket sort assumes that the input is generated by a random process that distributes elements uniformly and independently over the interval [0,1). page 201.


from random import sample, randint

def bucketsort(A): 

if __name__ == '__main__':
